# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JeremyShannon.com
email: jeremyeshannon@gmail.com
description:  #> # this means to ignore newlines until "baseurl:"
  - Udacity Self-Driving Car Engineer Nanodegree Fall 2017 <br>
  - MS in Electrical and Computer Engineering <br>
  - 15 years experience as electronics engineer and computer scientist
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:year/:month/:day/:title.html
#PRODUCTION
#url: "http://jeremyshannon.com" # the base hostname & protocol for your site
#DEV
url: "../" # the base hostname & protocol for your site
twitter_username:  jeremy_and
github_username:   jeremy-shannon
linkedin_username: jeremyeshannon

# Build settings
markdown: kramdown
